export enum UserRole {
  // ROLE_ADMIN = 'ROLE_ADMIN',
  // ROLE_STUDENT = 'ROLE_STUDENT',
  // ROLE_LECTURE = 'ROLE_LECTURER',
  ROLE_CEO = 'ROLE_CEO',
  ROLE_POST_OFFICE_MANAGER = 'ROLE_POST_OFFICE_MANAGER',
  ROLE_POST_OFFICE_EMPLOYEE = 'ROLE_POST_OFFICE_EMPLOYEE',
  ROLE_DEPOT_MANAGER = 'ROLE_DEPOT_MANAGER',
  ROLE_DEPOT_EMPLOYEE = 'ROLE_DEPOT_EMPLOYEE',
  ROLE_USER = 'ROLE_USER'
}
